name: check-email-sender
on: push

jobs:
    check-sender-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Check variables
              env:
                PAUSE: ${{ vars.PAUSE }}
              run: echo "Variable PAUSE=[$PAUSE]"

            - name: checker repo
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'

            - name: install pip
              run: python -m pip install --upgrade pip

            - name: install python packages
              run: pip install -r requirements.txt

            - name: execute script
              env:
                MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
                MAIL_TOKEN: ${{ secrets.MAIL_TOKEN }}
                PAUSE: ${{ vars.PAUSE }}

              run: python actionTest.py

            - name: test notice sender
              env:
                MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
                MAIL_TOKEN: ${{ secrets.MAIL_TOKEN }}

              run: python sender.py notice

            - name: test checkout sender
              env:
                MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
                MAIL_TOKEN: ${{ secrets.MAIL_TOKEN }}

              run: python sender.py checkout
