name: email-sender

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
    run-email-sender:
        runs-on: ubuntu-latest
        steps:
            - name: checker repo
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'

            - name: install pip
              run: python -m pip install --upgrade pip

            - name: install python packages
              run: pip install -r requirements.txt

            - name: execute timeChecker script
              env:
                MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
                MAIL_TOKEN: ${{ secrets.MAIL_TOKEN }}
                PAUSE: ${{ vars.PAUSE }}

              run: python timeChecker.py

