name: email-sender

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 0/3 * * *'

jobs:
    run-email-sender:
        runs-on: ubuntu-latest
        steps:
            - name: checker repo
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'

            - name: install pip
              run: python -m pip install --upgrade pip

            - name: install python packages
              run: pip install -r requirements.txt

            - name: execute timeChecker script daily
              if: github.event.schedule != '0 1 * * * *'
              env:
                MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
                MAIL_TOKEN: ${{ secrets.MAIL_TOKEN }}
                PAUSE: ${{ vars.PAUSE }}
                ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
                SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                SHEET_ID: ${{ vars.SHEET_ID }}
                SHEET_TOKEN: ${{ secrets.SHEET_TOKEN }}

              run: python timeChecker.py --daily

            - name: execute timeChecker script hourly
              env:
                MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
                MAIL_TOKEN: ${{ secrets.MAIL_TOKEN }}
                PAUSE: ${{ vars.PAUSE }}
                ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
                SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                SHEET_ID: ${{ vars.SHEET_ID }}
                SHEET_TOKEN: ${{ secrets.SHEET_TOKEN }}

              run: python timeChecker.py --hourly

